name: rfi-file-monitor
channels:
  - tom.schoonjans # to be removed when all packages have been updated on conda-forge!
  - conda-forge
dependencies:
  - python=3.8
  - gtk3
  - pygobject
  - setuptools
  - pip
  - boto3
  - munch
  - PyYAML
  - watchdog
  - adwaita-icon-theme
  - librsvg
  - paramiko
