name: rfi-file-monitor
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - gtk3
  - pygobject
  - setuptools
  - pip
  - boto3
  - munch
  - PyYAML
  - watchdog
  - adwaita-icon-theme
  - librsvg
  - paramiko
  - bugsnag
  - dropbox
  - keyring
  - tenacity
  - requests
  - pika
  - pip:
    - pyscicat
